### ISSUE TITLE
Shipping Costs

### ISSUE THREAD

**Issue by re4jh** [vitalybaev/php-google-merchant-feed#10]
Hi Vitaly ,

thank you for this nice one. It is very usefull for me.
At the moment i try to put shipping costs into my feed. 
As far as i know for Australia, Austria, Belgium, Canada, Czechia, France, Germany, Ireland Israel, Italy, the Netherlands, Poland, South Korea, Spain, Switzerland, the UK, and the US this is a mandatory field.

It consists of:
- optional country as ISO-3166
- optional region/postal_code/location_id/location_group
- optional service
- mandatory(!) price

(see: [https://support.google.com/merchants/answer/6324484](https://support.google.com/merchants/answer/6324484))

Do you have any solutions for that?

**Comment by vitalybaev** [comment]
Hi, @re4jh 
Thank you for your response!
I'll take a look into that and will implement this feature asap

**Comment by vitalybaev** [comment]
@re4jh I've published new `2.0.0` release with this feature and updated readme to show how it works
