### ISSUE TITLE
XML requires underscore

### ISSUE THREAD

**Issue by steveolotu** [vitalybaev/php-google-merchant-feed#15]
**Situation:** 
The constants in `php-google-merchant-feed/src/Product/Availability/Availability.php` contain whitespaces. 
**Problem:**
According to [Google](https://support.google.com/merchants/answer/3061198?hl=en), "XML feeds or XML API: Underscores are required, and are converted into white space when received".
**Solution suggestion:**
Create separate XML constants or dynamically replace spaces with underscores in case of XML.

**Comment by vitalybaev** [comment]
Fixed in `v2.5.0`
