### ISSUE TITLE
More than one Shipping?

### ISSUE THREAD

**Issue by romanklabal** [vitalybaev/php-google-merchant-feed#16]
Hi Vitaly,
seems like it is not possible to set up more than one shipping method right now? The Google Merchant docs state that you can enter up to 100 different shipping elements.

**XML**
To submit multiple delivery groups for an XML feed, include a separate attribute for each delivery group. You can submit up to 100 shipping attributes for each product.

```
<g:shipping>
   <g:country>US</g:country>
   <g:region>CA</g:region>
   <g:service>Express</g:service>
   <g:price>0 USD</g:price>
</g:shipping>
<g:shipping>
   <g:country>US</g:country>
   <g:region>OR</g:region>
   <g:service>Ground</g:service>
   <g:price>4.99 USD</g:price>
</g:shipping>
<g:shipping>
   <g:country>US</g:country>
   <g:region>WA</g:region>
   <g:service>Ground</g:service>
   <g:price>6.49 USD</g:price>
</g:shipping>
```

Any possibility of you adding an addShipping method?

Thanks!

**Comment by Samuell1** [comment]
Hey, facing same issue.

Tried to use addAttribute but without solution for this error `The writer cannot serialize objects of class: Vitalybaev\GoogleMerchant\PropertyBag`
```
$entry->addAttribute('shipping', $shipping->getPropertyBag()->setName('shipping'));
```

**Comment by vitalybaev** [comment]
Hi and sorry for the late answer. I'll take a look into it shortly

**Comment by Samuell1** [comment]
Thanks a lot was trying to solve it and PR it but didnt found solution yet.

**Comment by Samuell1** [comment]
@vitalybaev created a possible solution in PR. Not sure if its correct one.
