### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by michelmelo** [vitalybaev/php-google-merchant-feed#2]
how to use ?

**Comment by vitalybaev** [comment]
@michelmelo Thanks for the issue! I've added simple example to main readme.

**Comment by gelsonalves** [comment]
Can you help me?
I have been collecting the realtime data in my cron file to generate the google merchant xml. After adjusting the variables, I try to use your class to generate the xml file, but the following error is occurring:

PHP Fatal error:  Uncaught Vitalybaev\GoogleMerchant\Exception\InvalidArgumentException: Invalid availability property in /home/admin/web/mysite.com/public_html/cron/vendor/vitalybaev/google-merchant-feed/src/Product.php:130
Stack trace:
#0 /home/admin/web/mysite.com/public_html/cron/googleshopping.php(122): Vitalybaev\GoogleMerchant\Product->setAvailability('Dispon\xEDvel')
#1 {main}
  thrown in /home/admin/web/mysite.com/public_html/cron/vendor/vitalybaev/google-merchant-feed/src/Product.php on line 130

This is my code:


`<?php
$servername = "myserver";
$username = "myusername";
$password = "mypass";
$database = "mydb";

// Create connection
$conn = mysqli_connect($servername, $username, $password, $database);

// Check connection
if (!$conn) {
	echo "Erro na conexÃ£o";
      die("Connection failed: " . mysqli_connect_error());
} 

echo "ConexÃ£o Ok". "\n";


//collection data 

$sql = 'SELECT id, title, slug, description, price, shipping_cost, product_condition, user_id, category_id FROM products ORDER BY id;';

if (mysqli_query($conn, $sql)) {
    echo "ID captured". "\n";
}

$result = $conn->query($sql);
$row = $result->fetch_assoc();


require "/home/admin/web/mysite.com/public_html/cron/vendor/autoload.php";
//use Vitalybaev\GoogleMerchant\Feed;
//use Vitalybaev\GoogleMerchant\Product;
//use Vitalybaev\GoogleMerchant\Product\Shipping;
//use Vitalybaev\GoogleMerchant\Product\Availability\Availability;

// Create feed object
$feed = new \Vitalybaev\GoogleMerchant\Feed("Mysite", "https://mysite.com", "Mysite descryption");

// Put products to the feed ($products - some data from database for example)
foreach ($result as $product) {

	$chave = $row["id"];
	$titulo = $row["title"];
	$link = $row["slug"];
	$descricao = $row["description"];

	$frete = $row["shipping_cost"];
	if ($frete == 0) {
		$fretefinal = "Frete grátis";
	} else {
		$frete_tam = strlen($frete);
		$fretefinal = substr_replace($frete, ",", $frete_tam-2).substr($frete, $frete_tam-2);
	}
	
	$preco = $row["price"];
	$preco_tam = strlen($preco);
	$preco_final = substr_replace($preco, ",", $preco_tam-2).substr($preco, $preco_tam-2);
	$linkurl ="https://mysite.com/".$link;
	
	// Condiction

	$condi = $row["product_condition"];
	if ($condi == "used") {
		$condi = "Usado";
	   } elseif ($condi == "new") {
		$condi = "Novo";
	   } elseif ($condi == "good") {
		$condi = "Prestacao de servico";
		} elseif ($condi == "satisfactory") {
		$condi = "Animal";
		} elseif ($condi == "very_good") {
		$condi = "Permuta (Troca)";
	} else {
		$condi = "Novo";
	}


	// Image

	$sql_i = 'SELECT DISTINCT image_default FROM images WHERE images.product_id ='.$chave.'';
		if (mysqli_query($conn, $sql_i)) {
			echo "Image Ok". "\n";
		}
		$result_i = $conn->query($sql_i);
		$row_i = $result_i->fetch_assoc();
		$imagem= $row_i["image_default"];


	// Category

	$sql_c = 'SELECT DISTINCT name FROM categories_lang WHERE categories_lang.category_id ='.$chave.' AND lang_id = 2';
		if (mysqli_query($conn, $sql_c)) {
			echo "Category Ok". "\n";
		}
		$result_c = $conn->query($sql_c);
		$row_c = $result_c->fetch_assoc();
		$categoria= $row_c["name"];


	// Brand

	$sql_f = 'SELECT DISTINCT username FROM users WHERE users.id ='.$chave.'';
		if (mysqli_query($conn, $sql_f)) {
			echo "Brand Captured Ok". "\n";
		}
		$result_f = $conn->query($sql_f);
		$row_f = $result_f->fetch_assoc();
		$marca= $row_f["username"];
		$marca_name =$marca. " [xcom products]";



    $item = new \Vitalybaev\GoogleMerchant\Product();
    
    // Set common product properties
    $item->setId($chave);
    $item->setTitle($titulo);
    $item->setDescription($descricao);
    $item->setLink($linkurl);
    $item->setImage($imagem);
    $item->setAvailability("Disponível");
    $item->setPrice("{$product->price} BRL");
    $item->setGoogleCategory($categoria);
    $item->setBrand($marca_name);
    //$item->setGtin($product->barcode);
    $item->setCondition($condi);
    $item->setShipping($fretefinal);

    // Add this product to the feed
    $feed->addProduct($item);
}

// Here we get complete XML of the feed, that we could write to file or send directly
$feedXml = $feed->build();

?>`
