### ISSUE TITLE
Use multiple attributes with same name?

### ISSUE THREAD

**Issue by lenchik-ponchik** [vitalybaev/php-google-merchant-feed#7]
Hi. Can I use multiple attributes with same name?
For example additional_image_link.
For adding additional images up to 10 like google advises.
https://support.google.com/merchants/answer/6324370?hl=en
https://support.google.com/merchants/answer/7278995?hl=en

Thanks!

**Comment by vitalybaev** [comment]
Hi, @lenchik-ponchik!
Not for now, but I can fix it asap. It will be done in 1-2 days.

**Comment by vitalybaev** [comment]
@lenchik-ponchik, `v1.0.1` is out!
As described in the readme, you can use `$product->addAttribute`, which doesn't overwrite previous values, just adds a new one.
Thanks for the issue 😄
