### ISSUE TITLE
Parse error: syntax error, unexpected 'NEW' (T_NEW) in vendor/vitalybaev/google-merchant-feed/src/Product.php on line 306

### ISSUE THREAD

**Issue by hermans** [vitalybaev/php-google-merchant-feed#8]
Hi,

I use PHP 5.5 And show error.

```
public function setCondition($condition)
    {
        if (!in_array($condition, [
            Condition::NEW, Condition::REFURBISHED, Condition::USED,
        ])) {
            throw new InvalidArgumentException("Invalid condition property");
        }
        $this->setAttribute('condition', $condition, false);
        return $this;
    }
```

i changed it to be:

>  public function setCondition($condition)
>     {
>      
>         $this->setAttribute('condition', $condition, false);
>         return $this;
>     }

**Comment by vitalybaev** [comment]
@hermans Oh, sure! I forgot about this behavior on versions below 7. I've fixed the`setCondition` method by using plain strings for checking the input.
And I continue to investigate potential issues on 5.x
Thanks for the feedback
