### ISSUE TITLE
README information adjust

### ISSUE THREAD

**Issue by daywong1119** [vitalybaev/php-google-merchant-feed#9]
In the README page,  `use Vitalybaev\GoogleMerchant\Product\Availability\Availability;` will cause exception, but it is working in this path `use Vitalybaev\GoogleMerchant\Product\Availability\Availability;`

also; 

`$feedProduct->setAvailability(Availability::IN_STOCK);` should be `$item->setAvailability(Availability::IN_STOCK);`

**Comment by vitalybaev** [comment]
@daywong1119 you are absolutely right, thanks!
